version: '3.8'

services:
  data_cleaner:
    build:
      context: .
      dockerfile: docker_versions/Dockerfile.data_cleaner
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    networks:
      - medic_ai_network

  feature_selector:
    build:
      context: .
      dockerfile: docker_versions/Dockerfile.feature_selector
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - medic_ai_network

  anomaly_detector:
    build:
      context: .
      dockerfile: docker_versions/Dockerfile.anomaly_detector
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
    networks:
      - medic_ai_network

  model_trainer:
    build:
      context: .
      dockerfile: docker_versions/Dockerfile.model_trainer
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
    volumes:
      - ./models:/app/models
      - ./mlruns:/app/mlruns
    networks:
      - medic_ai_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - DATA_CLEANER_URL=http://data_cleaner:5001
      - FEATURE_SELECTOR_URL=http://feature_selector:5002
      - ANOMALY_DETECTOR_URL=http://anomaly_detector:5003
      - MODEL_TRAINER_URL=http://model_trainer:5004
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./uploads:/app/uploads
      - ./models:/app/models
      - ./mlruns:/app/mlruns
    depends_on:
      - data_cleaner
      - feature_selector
      - anomaly_detector
      - model_trainer
    networks:
      - medic_ai_network

networks:
  medic_ai_network:
    driver: bridge