version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      # Classification services
      - DATA_CLEANER_URL=http://data_cleaner:5001
      - FEATURE_SELECTOR_URL=http://feature_selector:5002
      - ANOMALY_DETECTOR_URL=http://anomaly_detector:5003
      - MODEL_COORDINATOR_URL=http://model_coordinator:5020
      - MEDICAL_ASSISTANT_URL=http://medical_assistant:5005
      - AUGMENTATION_SERVICE_URL=http://augmentation_service:5023
      - MODEL_TRAINING_SERVICE_URL=http://model_training_service:5021
      
      # Regression services
      - REGRESSION_DATA_CLEANER_URL=http://regression-data-cleaner:5031
      - REGRESSION_FEATURE_SELECTOR_URL=http://regression-feature-selector:5032
      - REGRESSION_MODEL_COORDINATOR_URL=http://regression-model-coordinator:5040
      - REGRESSION_PREDICTOR_SERVICE_URL=http://regression-predictor-service:5050
      
      # Database configuration
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DB=${MYSQL_DB}
      
      # Other settings
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT}
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
      - AZURE_CONTAINER=${AZURE_CONTAINER}
    volumes:
      - .:/app
    networks:
      - deepmed-network
      - regression-network
    depends_on:
      - regression-data-cleaner
      - regression-feature-selector
      - regression-model-coordinator
      - regression-predictor-service

networks:
  deepmed-network:
    external: true
  regression-network:
    external: true 