version: '3'

services:
  # Data Cleaner service (reused from classification system)
  data-cleaner:
    build:
      context: ../docker_versions
      dockerfile: Dockerfile.data_cleaner
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./logs:/app/logs
    networks:
      - deepmed-regression-network

  # Feature Selector service (reused from classification system)
  feature-selector:
    build:
      context: ../docker_versions
      dockerfile: Dockerfile.feature_selector
    ports:
      - "5002:5002"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./logs:/app/logs
    networks:
      - deepmed-regression-network

  # Anomaly Detector service (reused from classification system)
  anomaly-detector:
    build:
      context: ../docker_versions
      dockerfile: Dockerfile.anomaly_detector
    ports:
      - "5003:5003"
    volumes:
      - ./logs:/app/logs
    networks:
      - deepmed-regression-network

  # Model Coordinator (orchestrates regression model services)
  model_coordinator:
    build:
      context: .
      dockerfile: Dockerfile.model_coordinator
    container_name: regression_model_coordinator
    ports:
      - "6020:6020"
    environment:
      - PORT=6020
      - IS_DOCKER=true
      - LINEAR_REGRESSION_URL=http://linear_regression:6010
      - RIDGE_REGRESSION_URL=http://ridge_regression:6011
      - LASSO_REGRESSION_URL=http://lasso_regression:6012
      - RANDOM_FOREST_REGRESSOR_URL=http://random_forest_regressor:6013
      - SVR_URL=http://svr:6014
      - MLFLOW_TRACKING_URI=file:///app/mlruns
    volumes:
      - ./logs:/app/logs
      - ./mlruns:/app/mlruns
    networks:
      - deepmed-regression-network
    restart: on-failure

  # Individual regression model services
  linear_regression:
    build:
      context: .
      dockerfile: Dockerfile.linear_regression
    ports:
      - "6010:6010"
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns
    volumes:
      - ./logs:/app/logs
      - ./saved_models:/app/saved_models
      - ./mlruns:/app/mlruns
    networks:
      - deepmed-regression-network

  ridge_regression:
    build:
      context: .
      dockerfile: Dockerfile.ridge_regression
    ports:
      - "6011:6011"
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns
    volumes:
      - ./logs:/app/logs
      - ./saved_models:/app/saved_models
      - ./mlruns:/app/mlruns
    networks:
      - deepmed-regression-network

  lasso_regression:
    build:
      context: .
      dockerfile: Dockerfile.lasso_regression
    ports:
      - "6012:6012"
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns
    volumes:
      - ./logs:/app/logs
      - ./saved_models:/app/saved_models
      - ./mlruns:/app/mlruns
    networks:
      - deepmed-regression-network

  random_forest_regressor:
    build:
      context: .
      dockerfile: Dockerfile.random_forest_regressor
    ports:
      - "6013:6013"
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns
    volumes:
      - ./logs:/app/logs
      - ./saved_models:/app/saved_models
      - ./mlruns:/app/mlruns
    networks:
      - deepmed-regression-network
      
  svr:
    build:
      context: .
      dockerfile: Dockerfile.svr
    ports:
      - "6014:6014"
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns
    volumes:
      - ./logs:/app/logs
      - ./saved_models:/app/saved_models
      - ./mlruns:/app/mlruns
    networks:
      - deepmed-regression-network

networks:
  deepmed-regression-network:
    driver: bridge 