FROM python:3.9-slim

WORKDIR /app

COPY requirements_iep.txt .
RUN pip install --no-cache-dir -r requirements_iep.txt

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Default command - will be overridden in docker-compose
CMD ["python", "app.py"] 