version: '3'

services:
  model-training:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5100:5100"
    volumes:
      - ./model_service.py:/app/model_service.py
    environment:
      - PORT=5100
    restart: always
    networks:
      - deepmed-network

  data-processing:
    build:
      context: .
      dockerfile: Dockerfile.iep
    ports:
      - "5101:5101"
    volumes:
      - ./data_processing_service.py:/app/data_processing_service.py
    environment:
      - PORT=5101
    restart: always
    command: python data_processing_service.py
    networks:
      - deepmed-network

  data-augmentation:
    build:
      context: .
      dockerfile: Dockerfile.iep
    ports:
      - "5102:5102"
    volumes:
      - ./data_augmentation_service.py:/app/data_augmentation_service.py
    environment:
      - PORT=5102
    restart: always
    command: python data_augmentation_service.py
    networks:
      - deepmed-network

  image-processing-eep:
    build:
      context: .
      dockerfile: Dockerfile.iep
    ports:
      - "5103:5103"
    volumes:
      - ./image_processing_eep.py:/app/image_processing_eep.py
    environment:
      - PORT=5103
    restart: always
    command: python image_processing_eep.py
    depends_on:
      - model-training
      - data-processing
      - data-augmentation
    networks:
      - deepmed-network

networks:
  deepmed-network:
    driver: bridge 