version: '3'

services:
  model-training-service:
    build:
      context: ./images_classification
      dockerfile: Dockerfile
    ports:
      - "5021:5021"
    restart: unless-stopped
    volumes:
      - ./images_classification/app.py:/app/app.py
    environment:
      - PORT=5021
    networks:
      - deepmed-network

  augmentation-service:
    build:
      context: ./data_augmentation
      dockerfile: Dockerfile
    ports:
      - "5023:5023"
    restart: unless-stopped
    volumes:
      - ./data_augmentation/data_augmentation.py:/app/data_augmentation.py
      - ./data_augmentation/augment_service.py:/app/augment_service.py
    environment:
      - PORT=5023
    networks:
      - deepmed-network
      
  pipeline-service:
    build:
      context: ./pipeline
      dockerfile: Dockerfile
    ports:
      - "5025:5025"
    restart: unless-stopped
    volumes:
      - ./pipeline/app.py:/app/app.py
    environment:
      - PORT=5025
      - AUGMENTATION_SERVICE_URL=http://augmentation-service:5023
      - MODEL_TRAINING_SERVICE_URL=http://model-training-service:5021
    networks:
      - deepmed-network
    depends_on:
      - augmentation-service
      - model-training-service
  
  anomaly-detector-eep:
    build:
      context: ./eep_anomaly_detector
      dockerfile: Dockerfile_eep
    ports:
      - "5030:5030"
    restart: unless-stopped
    volumes:
      - ./eep_anomaly_detector/anomaly_detector_eep.py:/app/anomaly_detector_eep.py
    environment:
      - PORT=5030
      - ANOMALY_DETECTION_SERVICE_URL=http://anomaly-detection-service:5029
    networks:
      - deepmed-network
    depends_on:
      - anomaly-detection-service
      
  anomaly-detection-service:
    build:
      context: ./anomaly_detector
      dockerfile: Dockerfile
    ports:
      - "5029:5029"
    restart: unless-stopped
    volumes:
      - ./anomaly_detector/anomaly_detection_service.py:/app/anomaly_detection_service.py
    shm_size: '4gb'
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          memory: 2G
    environment:
      - PORT=5029
    networks:
      - deepmed-network

  predictor-service:
    build:
      context: ./predictor
      dockerfile: Dockerfile
    ports:
      - "5100:5100"
    restart: unless-stopped
    volumes:
      - ./predictor/predictor.py:/app/predictor.py
    environment:
      - PORT=5100
    networks:
      - deepmed-network


networks:
  deepmed-network:
    driver: bridge 