version: '3'

services:
  model-training-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5021:5021"
    restart: unless-stopped
    volumes:
      - ./model_service.py:/app/model_service.py
    environment:
      - PORT=5021
    networks:
      - deepmed-network

  augmentation-service:
    build:
      context: .
      dockerfile: Dockerfile_augment
    ports:
      - "5023:5023"
    restart: unless-stopped
    volumes:
      - ./data_augmentation.py:/app/data_augmentation.py
      - ./augment_service.py:/app/augment_service.py
    environment:
      - PORT=5023
    networks:
      - deepmed-network
      
  pipeline-service:
    build:
      context: .
      dockerfile: Dockerfile_pipeline
    ports:
      - "5025:5025"
    restart: unless-stopped
    volumes:
      - ./pipeline_service.py:/app/pipeline_service.py
    environment:
      - PORT=5025
      - AUGMENTATION_SERVICE_URL=http://augmentation-service:5023
      - MODEL_TRAINING_SERVICE_URL=http://model-training-service:5021
    networks:
      - deepmed-network
    depends_on:
      - augmentation-service
      - model-training-service
      
  object-detection-service:
    build:
      context: .
      dockerfile: Dockerfile_object_detection
    ports:
      - "5027:5027"
    restart: unless-stopped
    volumes:
      - ./object_detection_service.py:/app/object_detection_service.py
    environment:
      - PORT=5027
    networks:
      - deepmed-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  deepmed-network:
    driver: bridge 