version: '3'

services:
  monitoring:
    build: .
    ports:
      - "5432:5432"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - FLASK_ENV=production
      # Core Services
      - DATA_CLEANER_URL=http://host.docker.internal:5001
      - FEATURE_SELECTOR_URL=http://host.docker.internal:5002
      - ANOMALY_DETECTOR_URL=http://host.docker.internal:5003
      # Model Services
      - MODEL_COORDINATOR_URL=http://host.docker.internal:5020
      - MODEL_TRAINING_SERVICE_URL=http://host.docker.internal:5021
      - LOGISTIC_REGRESSION_URL=http://host.docker.internal:5010
      - DECISION_TREE_URL=http://host.docker.internal:5011
      - RANDOM_FOREST_URL=http://host.docker.internal:5012
      - SVM_URL=http://host.docker.internal:5013
      - KNN_URL=http://host.docker.internal:5014
      - NAIVE_BAYES_URL=http://host.docker.internal:5015
      # Medical AI Services
      - MEDICAL_ASSISTANT_URL=http://host.docker.internal:5005
      - PIPELINE_SERVICE_URL=http://host.docker.internal:5025
      # Image Processing Services
      - AUGMENTATION_SERVICE_URL=http://host.docker.internal:5023
      - ANOMALY_DETECTION_SERVICE_URL=http://host.docker.internal:5029
      - SEMANTIC_SEGMENTATION_SERVICE_URL=http://host.docker.internal:5031
      # Predictor Services
      - TABULAR_PREDICTOR_URL=http://host.docker.internal:5100
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  prometheus:
    build: ./prometheus
    ports:
      - "0.0.0.0:9090:9090"
    volumes:
      - prometheus_data:/prometheus
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  grafana:
    build: ./grafana
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=deepmed
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
    depends_on:
      - prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  prometheus_data:
  grafana_data: 