#version: '3'

services:
  # Regression Data Cleaner service
  regression-data-cleaner:
    build:
      context: ./regression_data_cleaner
      dockerfile: Dockerfile
    ports:
      - "5031:5031"
    environment:
      - PORT=5031
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./logs:/app/logs
    networks:
      - regression-network

  # Regression Feature Selector service
  regression-feature-selector:
    build:
      context: ./regression_feature_selector
      dockerfile: Dockerfile
    ports:
      - "5032:5032"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./logs:/app/logs
    networks:
      - regression-network

  # Model Coordinator for Regression
  regression-model-coordinator:
    build:
      context: ./regression_model_coordinator
      dockerfile: Dockerfile
    container_name: regression_model_coordinator
    ports:
      - "5040:5040"
    environment:
      - PORT=5040
      - IS_DOCKER=true
      - LINEAR_REGRESSION_URL=http://linear_regression:5041
      - LASSO_REGRESSION_URL=http://lasso_regression:5042
      - RIDGE_REGRESSION_URL=http://ridge_regression:5043
      - RANDOM_FOREST_REGRESSION_URL=http://random_forest_regression:5044
      - KNN_REGRESSION_URL=http://knn_regression:5045
      - XGBOOST_REGRESSION_URL=http://xgboost_regression:5046
      - MLFLOW_TRACKING_URI=file:///app/mlruns
      # Disabled database operations
      - DB_DISABLED=true
      # Azure Blob Storage for model saving (these will be passed from environment)
      - AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT}
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
      - AZURE_CONTAINER=${AZURE_CONTAINER}
    volumes:
      - ./logs:/app/logs
      - ./mlruns:/app/mlruns
      - ./saved_models:/app/saved_models
    networks:
      - regression-network
      - deepmed-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure

  # Individual regression model services
  linear_regression:
    build:
      context: ./linear_regression
      dockerfile: Dockerfile
    ports:
      - "5041:5041"
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns
      - DB_DISABLED=true
    volumes:
      - ./logs:/app/logs
      - ./saved_models:/app/saved_models
      - ./mlruns:/app/mlruns
    networks:
      - regression-network

  lasso_regression:
    build:
      context: ./lasso_regression
      dockerfile: Dockerfile
    ports:
      - "5042:5042"
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns
      - DB_DISABLED=true
    volumes:
      - ./logs:/app/logs
      - ./saved_models:/app/saved_models
      - ./mlruns:/app/mlruns
    networks:
      - regression-network

  ridge_regression:
    build:
      context: ./ridge_regression
      dockerfile: Dockerfile
    ports:
      - "5043:5043"
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns
      - DB_DISABLED=true
    volumes:
      - ./logs:/app/logs
      - ./saved_models:/app/saved_models
      - ./mlruns:/app/mlruns
    networks:
      - regression-network

  random_forest_regression:
    build:
      context: ./random_forest_regression
      dockerfile: Dockerfile
    ports:
      - "5044:5044"
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns
      - DB_DISABLED=true
    volumes:
      - ./logs:/app/logs
      - ./saved_models:/app/saved_models
      - ./mlruns:/app/mlruns
    networks:
      - regression-network
      
  knn_regression:
    build:
      context: ./knn_regression
      dockerfile: Dockerfile
    ports:
      - "5045:5045"
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns
      - DB_DISABLED=true
    volumes:
      - ./logs:/app/logs
      - ./saved_models:/app/saved_models
      - ./mlruns:/app/mlruns
    networks:
      - regression-network
      
  xgboost_regression:
    build:
      context: ./xgboost_regression
      dockerfile: Dockerfile
    ports:
      - "5046:5046"
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns
      - DB_DISABLED=true
    volumes:
      - ./logs:/app/logs
      - ./saved_models:/app/saved_models
      - ./mlruns:/app/mlruns
    networks:
      - regression-network

  # Regression Predictor Service
  regression-predictor-service:
    build:
      context: ./regression_predictor
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    restart: unless-stopped
    volumes:
      - ./regression_predictor/predictor.py:/app/predictor.py
    environment:
      - PORT=5050
      # Azure Blob Storage for model download (these will be passed from environment)
      - AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT}
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
      - AZURE_CONTAINER=${AZURE_CONTAINER}
    networks:
      - regression-network

networks:
  regression-network:
    driver: bridge
  deepmed-network:
    driver: bridge 