global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_timeout: 10s

  - job_name: 'monitoring_service'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['monitoring:5432']
    scrape_timeout: 10s
    
  # Core Services
  - job_name: 'data_cleaner'
    metrics_path: /metrics
    static_configs:
      - targets: ['docker_versions-data-cleaner-1:5001']
    scrape_timeout: 10s
    scheme: http
    
  - job_name: 'feature_selector'
    metrics_path: /metrics
    static_configs:
      - targets: ['docker_versions-feature-selector-1:5002']
    scrape_timeout: 10s
    scheme: http
    
  - job_name: 'anomaly_detector'
    metrics_path: /metrics
    static_configs:
      - targets: ['docker_versions-anomaly-detector-1:5003']
    scrape_timeout: 10s
    scheme: http
  
  # Model Services
  - job_name: 'model_coordinator'
    metrics_path: /metrics
    static_configs:
      - targets: ['model_coordinator:5020']
    scrape_timeout: 10s
    scheme: http
  
  - job_name: 'model_training_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['docker_versions-model-training-service-1:5021']
    scrape_timeout: 10s
    scheme: http
  
  - job_name: 'logistic_regression'
    metrics_path: /metrics
    static_configs:
      - targets: ['docker_versions-logistic_regression-1:5010']
    scrape_timeout: 10s
    scheme: http
    
  - job_name: 'decision_tree'
    metrics_path: /metrics
    static_configs:
      - targets: ['docker_versions-decision_tree-1:5011']
    scrape_timeout: 10s
    scheme: http
    
  - job_name: 'random_forest'
    metrics_path: /metrics
    static_configs:
      - targets: ['docker_versions-random_forest-1:5012']
    scrape_timeout: 10s
    scheme: http
    
  - job_name: 'svm'
    metrics_path: /metrics
    static_configs:
      - targets: ['docker_versions-svm-1:5013']
    scrape_timeout: 10s
    scheme: http
    
  - job_name: 'knn'
    metrics_path: /metrics
    static_configs:
      - targets: ['docker_versions-knn-1:5014']
    scrape_timeout: 10s
    scheme: http
    
  - job_name: 'naive_bayes'
    metrics_path: /metrics
    static_configs:
      - targets: ['docker_versions-naive_bayes-1:5015']
    scrape_timeout: 10s
    scheme: http
      
  # Medical AI Services
  - job_name: 'medical_assistant'
    metrics_path: /metrics
    static_configs:
      - targets: ['docker_versions-medical-assistant-1:5005']
    scrape_timeout: 10s
    scheme: http
    
  - job_name: 'pipeline_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['docker_versions-pipeline-service-1:5025']
    scrape_timeout: 10s
    scheme: http
  
  # Image Processing Services
  - job_name: 'augmentation_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['docker_versions-augmentation-service-1:5023']
    scrape_timeout: 10s
    scheme: http
  
  - job_name: 'anomaly_detection_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['docker_versions-anomaly-detection-service-1:5029']
    scrape_timeout: 10s
    scheme: http
  
  # Predictor Services
  - job_name: 'tabular_predictor'
    metrics_path: /metrics
    static_configs:
      - targets: ['docker_versions-tabular-predictor-service-1:5100']
    scrape_timeout: 10s
    scheme: http 