global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'monitoring_service'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['monitoring:5432']
    
  # Core Services
  - job_name: 'data_cleaner'
    metrics_path: /metrics
    static_configs:
      - targets: ['20.119.81.37:5001']
    
  - job_name: 'feature_selector'
    metrics_path: /metrics
    static_configs:
      - targets: ['20.119.81.37:5002']
    
  - job_name: 'anomaly_detector'
    metrics_path: /metrics
    static_configs:
      - targets: ['20.119.81.37:5003']
  
  # Model Services
  - job_name: 'model_coordinator'
    metrics_path: /metrics
    static_configs:
      - targets: ['20.119.81.37:5020']
  
  - job_name: 'model_training_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['20.119.81.37:5021']
  
  - job_name: 'logistic_regression'
    metrics_path: /metrics
    static_configs:
      - targets: ['20.119.81.37:5010']
    
  - job_name: 'decision_tree'
    metrics_path: /metrics
    static_configs:
      - targets: ['20.119.81.37:5011']
    
  - job_name: 'random_forest'
    metrics_path: /metrics
    static_configs:
      - targets: ['20.119.81.37:5012']
    
  - job_name: 'svm'
    metrics_path: /metrics
    static_configs:
      - targets: ['20.119.81.37:5013']
    
  - job_name: 'knn'
    metrics_path: /metrics
    static_configs:
      - targets: ['20.119.81.37:5014']
    
  - job_name: 'naive_bayes'
    metrics_path: /metrics
    static_configs:
      - targets: ['20.119.81.37:5015']
      
  # Medical AI Services
  - job_name: 'medical_assistant'
    metrics_path: /metrics
    static_configs:
      - targets: ['20.119.81.37:5005']
    
  - job_name: 'pipeline_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['20.119.81.37:5025']
  
  # Image Processing Services
  - job_name: 'augmentation_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['20.119.81.37:5023']
  
  - job_name: 'anomaly_detection_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['20.119.81.37:5029']
  
  # Predictor Services
  - job_name: 'tabular_predictor'
    metrics_path: /metrics
    static_configs:
      - targets: ['20.119.81.37:5100'] 