version: '3.8'
services:
  embedding_service:
    build:
      context: ./embedding_service
      dockerfile: Dockerfile
    ports:
      - "5201:5201"
    env_file:
      - ../.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ../logs:/app/logs
    networks:
      - deepmed-network

  vector_search_service:
    build:
      context: ./vector_search_service
    ports:
      - "5202:5202"
    env_file:
      - ../.env
    networks:
      - deepmed-network



  llm_generator_service:
    build:
      context: ./llm_generator_service
      dockerfile: Dockerfile
    ports:
      - "5203:5203"
    env_file:
      - ../.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ../logs:/app/logs
    networks:
      - deepmed-network

  chatbot_gateway:
    build:
      context: ./chatbot_gateway
      dockerfile: Dockerfile
    ports:
      - "5204:5204"
    env_file:
      - ../.env
    environment:
      - EMBEDDING_URL=http://embedding_service:5201
      - VECTOR_URL=http://vector_search_service:5202
      - LLM_URL=http://llm_generator_service:5203
      - SYSTEM_PROMPT=${SYSTEM_PROMPT}
    volumes:
      - ../logs:/app/logs
    networks:
      - deepmed-network

networks:
  deepmed-network:
    driver: bridge
