name: Build and Push Multi-Service Images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.generate_tag.outputs.git_sha }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Free up disk space
      run: |
        echo "Disk space before cleanup:"
        df -h
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache
        echo "Disk space after cleanup:"
        df -h

    - name: Generate Tag
      id: generate_tag
      run: |
        GIT_SHA=$(git rev-parse --short=7 HEAD)
        echo "git_sha=$GIT_SHA" >> $GITHUB_OUTPUT
        echo "Generated tag: $GIT_SHA"
        # Create a file with the tag for other workflows
        echo "$GIT_SHA" > image_tag.txt

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Tag Images
      run: |
        # Build with default tag (latest)
        docker compose -f docker_versions/docker-compose.yml build
        
        # Tag with Git SHA
        GIT_SHA=${{ steps.generate_tag.outputs.git_sha }}
        
        # Loop through services and tag with SHA
        for service in $(docker compose -f docker_versions/docker-compose.yml config --services); do
          image_name=$(docker compose -f docker_versions/docker-compose.yml config | grep "image:" | grep "$service" | awk '{print $2}')
          # Tag with SHA
          docker tag $image_name ${image_name%:*}:$GIT_SHA
          echo "Tagged $image_name as ${image_name%:*}:$GIT_SHA"
        done

    - name: Push Images
      run: |
        GIT_SHA=${{ steps.generate_tag.outputs.git_sha }}
        
        # Push latest tags
        docker compose -f docker_versions/docker-compose.yml push
        
        # Push SHA tags
        for service in $(docker compose -f docker_versions/docker-compose.yml config --services); do
          image_name=$(docker compose -f docker_versions/docker-compose.yml config | grep "image:" | grep "$service" | awk '{print $2}')
          # Push SHA tag
          docker push ${image_name%:*}:$GIT_SHA
          echo "Pushed ${image_name%:*}:$GIT_SHA"
        done
        
    - name: Upload image tag artifact
      uses: actions/upload-artifact@v4
      with:
        name: image-tag
        path: image_tag.txt
        retention-days: 7
