name: Build and Push Multi-Service Images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Free up disk space
      run: |
        echo "Disk space before cleanup:"
        df -h
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache
        echo "Disk space after cleanup:"
        df -h

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Images
      run: |
        # Build with default tag (latest)
        echo "Building Docker images..."
        docker compose -f docker_versions/docker-compose.yml build
        
        # Push latest tags
        echo "Pushing Docker images to DockerHub..."
        docker compose -f docker_versions/docker-compose.yml push
        
        echo "All images built and pushed successfully!"
