name: Prepare and Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Free up disk space
        run: |
          echo "Disk space before cleanup:" && df -h
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache || true
          echo "Disk space after cleanup:" && df -h

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull & switch Docker containers (fast)
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.SERVER_IP }} bash << 'EOF'
            cd ~/DeepMed
            docker-compose pull
            docker-compose up -d --remove-orphans
          EOF
