name: Prepare and Deploy to Production

on:
  workflow_run:
    workflows: ["Docker Services Health Check"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Free up disk space
        run: |
          echo "Disk before cleanup:" && df -h
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache || true
          echo "Disk after cleanup:" && df -h

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull & switch Docker containers (fast)
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.SERVER_IP }} bash << 'EOF'
            cd ~/DeepMed/docker_versions
            echo '${{ secrets.PASSWORD }}' | sudo -S docker compose pull
            echo '${{ secrets.PASSWORD }}' | sudo -S docker compose up -d --remove-orphans
          EOF
