name: Setup Test Environment

on:
  push:
    branches:
      - main

jobs:
  setup-test-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}

      - name: Wait for SSH to be available
        run: |
          for i in {1..12}; do
            if ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.TEST_SERVER_IP }} 'echo SSH ready' &>/dev/null; then
              echo "✅ SSH connection established"
              break
            else
              echo "⏳ Waiting for SSH..."
              sleep 10
            fi
          done

      - name: Update & install Python on test VM
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.TEST_SERVER_IP }} bash << 'EOF'
            sudo apt-get update -y
            if ! command -v python3 &> /dev/null; then sudo apt-get install -y python3; fi
            if ! command -v pip3 &> /dev/null; then sudo apt-get install -y python3-pip; fi
          EOF

      - name: Ensure DeepMed directory exists
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.TEST_SERVER_IP }} "mkdir -p ~/DeepMed"

      - name: Copy requirements.txt & install deps
        run: |
          scp -o StrictHostKeyChecking=no requirements.txt azureuser@${{ secrets.TEST_SERVER_IP }}:~/DeepMed/requirements.txt
          ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.TEST_SERVER_IP }} "pip3 install -r ~/DeepMed/requirements.txt"
