name: Setup Test Environment

on:
  push:
    branches:
      - main

jobs:
  setup-test-environment:
    name: Setup Test Environment
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup SSH connection
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}

      - name: Add Test Server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.TEST_SERVER_IP }} >> ~/.ssh/known_hosts
      
      - name: Update System Packages
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.TEST_SERVER_IP }} "sudo apt update"
      
      - name: Install Python and Pip (if missing)
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.TEST_SERVER_IP }} "
            if ! command -v python3 &> /dev/null; then sudo apt install -y python3; fi
            if ! command -v pip3 &> /dev/null; then sudo apt install -y python3-pip; fi
          "
      
      - name: Copy requirements.txt to VM
        run: |
          scp -o StrictHostKeyChecking=no requirements.txt azureuser@${{ secrets.TEST_SERVER_IP }}:~/DeepMed/requirements.txt
      
      - name: Install Python Requirements
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.TEST_SERVER_IP }} "pip3 install -r ~/DeepMed/requirements.txt"
